// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3_154-elsrYXj9ZanD9WcqQbzUx1wiIY',
    appId: '1:640247507565:web:ad8778a2ba2744c0116d64',
    messagingSenderId: '640247507565',
    projectId: 'aara-58c45',
    authDomain: 'aara-58c45.firebaseapp.com',
    storageBucket: 'aara-58c45.firebasestorage.app',
    measurementId: 'G-7KY7QNJQ8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26YDWQEp-vVGB3J09R24ugcwZSbNkbhQ',
    appId: '1:640247507565:android:4b2d72d3678cd55c116d64',
    messagingSenderId: '640247507565',
    projectId: 'aara-58c45',
    storageBucket: 'aara-58c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGTKdIeSoJzSsdIwjW9VzMqHaIDREe7vA',
    appId: '1:640247507565:ios:06488cea027d0463116d64',
    messagingSenderId: '640247507565',
    projectId: 'aara-58c45',
    storageBucket: 'aara-58c45.firebasestorage.app',
    iosBundleId: 'com.example.aara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGTKdIeSoJzSsdIwjW9VzMqHaIDREe7vA',
    appId: '1:640247507565:ios:06488cea027d0463116d64',
    messagingSenderId: '640247507565',
    projectId: 'aara-58c45',
    storageBucket: 'aara-58c45.firebasestorage.app',
    iosBundleId: 'com.example.aara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3_154-elsrYXj9ZanD9WcqQbzUx1wiIY',
    appId: '1:640247507565:web:f2dbe464bebeb637116d64',
    messagingSenderId: '640247507565',
    projectId: 'aara-58c45',
    authDomain: 'aara-58c45.firebaseapp.com',
    storageBucket: 'aara-58c45.firebasestorage.app',
    measurementId: 'G-YKPDB87GEC',
  );
}
