type User @table {
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  firstName: String
  lastName: String
  shippingAddress: String
  billingAddress: String
}

type Product @table {
  name: String!
  price: Float!
  description: String!
  category: String!
  createdAt: Timestamp!
  imageUrl: String
  color: String
  size: String
  material: String
}

type Cart @table {
  user: User!
  createdAt: Timestamp!
}

type CartItem @table {
  cart: Cart!
  product: Product!
  quantity: Int!
  priceAtTimeOfAddition: Float!
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  shippingAddress: String!
  status: String!
}

type OrderItem @table {
  order: Order!
  product: Product!
  quantity: Int!
  priceAtTimeOfPurchase: Float!
}